<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="ILRepacker" AfterTargets="Build">

    <ItemGroup>
      <ILRepackInputAssemblies Include="$(TargetPath)" />
      <ILRepackInputAssemblies Include="$(MSBuildProjectDirectory)\libs\EpicLootAPI.dll" />
    </ItemGroup>

    <Message
      Text="Merging EpicLootAPI.dll into $(TargetPath)"
      Importance="high" />

    <ILRepack
      Parallel="true"
      DebugInfo="true"
      Internalize="true"
      InputAssemblies="@(ILRepackInputAssemblies)"
      OutputFile="$(TargetPath)"
      TargetKind="SameAsPrimaryAssembly"
      LibraryPath="$(TargetDir);$(MSBuildProjectDirectory)\libs" />

  </Target>

</Project>